const teamData = [
    {
    nombreCompleto: 'Adolfo Agostini',
    rol: 'Animador',
    linkedin: 'URL_LinkedIn_Adolfo',
    email: 'email_adolfo@example.com',
    github: 'URL_GitHub_Adolfo',
    img: require('../assets/Fotos_Perfil/Adolfo.jpg'),
    },
    {
    nombreCompleto: 'Agustin Ponce',
    rol: 'Sonidista',
    linkedin: ' ',
    email: ' ',
    github: ' ',
    img: require('../assets/Fotos_Perfil/Agustin.jpg'), 
    },
    {
    nombreCompleto: "Aylen Rodriguez",
    rol: 'Animadora',
    linkedin: ' ',
    email: ' ',
    github: ' ',
    img: require('../assets/Fotos_Perfil/Aylen.jpg'), 
    },
    {
    nombreCompleto: 'Dario Mamani',
    rol: 'Programador',
    linkedin: '',
    email: '',
    github: '',
    img: require('../assets/Fotos_Perfil/Dario.jpg'), 
    },
    {
    nombreCompleto: 'Evelyn Ramos',
    rol: 'Programadora',
    linkedin: '',
    email: 'eve.lol@gmail.com',
    github: 'dsad',
    img: require('../assets/Fotos_Perfil/Evelyn.jpg'), 
    },
    {
    nombreCompleto: 'Gabriel Flores',
    rol: 'Sonidista',
    linkedin: '',
    email: '',
    github: '',
    img: require('../assets/Fotos_Perfil/Gabriel.jpg'), 
    },
    {
    nombreCompleto: 'Guillermo Arostegui',
    rol: 'Sonidista',
    linkedin: '',
    email: '',
    github: '',
    img: require('../assets/Fotos_Perfil/Guillermo.jpg'), 
    },
    {
    nombreCompleto: 'Jonatan Calapeña',
    rol: 'Sonidista',
    linkedin: '',
    email: '',
    github: '',
    img: require('../assets/Fotos_Perfil/Jonathan.jpg'), 
    },
    {
    nombreCompleto: 'Nataniel Cazon',
    rol: 'Programador',
    linkedin: '',
    email: '',
    github: '',
    img: require('../assets/Fotos_Perfil/Nataniel.jpg'), 
    },
    {
    nombreCompleto: 'Ariel Vega',
    rol: 'Programador',
    linkedin: '',
    email: '',
    github: '',
    img: require('../assets/Fotos_Perfil/Vega.jpg'), 
    },
    {
    nombreCompleto: 'Ezequiel Ozan',
    rol: 'Sonido',
    linkedin: '',
    email: '',
    github: '',
    img: require('../assets/Fotos_Perfil/Ezequiel.jpg'), 
    },
];

export default teamData;