const teamData = [
  {
    nombreCompleto: "Adolfo Agostini",
    roles: ["Animador"],
    linkedin: "URL_LinkedIn_Adolfo",
    github: "URL_GitHub_Adolfo",
    instagram: " ",
    facebook: " ",
    twitter: " ",
    img: require("../assets/Fotos_Perfil/Adolfo.jpg"),
  },
  {
    nombreCompleto: "Guillermo Javier Arostegui",
    roles: ["Sonidista"],
    linkedin: "",
    github: "",
    instagram: "",
    facebook: "",
    twitter: "",
    img: require("../assets/Fotos_Perfil/Guillermo.jpg"),
  },
  {
    nombreCompleto: "Jonatan Fernando Calapeña",
    roles: ["Sonidista", "Programador"],
    linkedin: "",
    github: "",
    instagram: "",
    facebook: "",
    twitter: "",
    img: require("../assets/Fotos_Perfil/Jonatan.jpg"),
  },
  {
    nombreCompleto: "Nataniel Cazon",
    roles: ["Programador", "Animador"],
    linkedin: "https://www.linkedin.com/in/nataniel-cazon-984540246/",
    github: "https://github.com/NatanielCZN",
    instagram: "",
    facebook: "",
    twitter: "",
    img: require("../assets/Fotos_Perfil/Nataniel.jpg"),
  },
  {
    nombreCompleto: "Gabriel Flores",
    roles: ["Sonidista", "Narrador"],
    linkedin: "https://www.linkedin.com/in/juan-gabriel-flores-997208158/",
    github: "https://github.com/NozomiProjects",
    instagram: "https://www.instagram.com/gabito2710/",
    facebook: "",
    twitter: "",
    img: require("../assets/Fotos_Perfil/Gabriel.jpg"),
  },
  {
    nombreCompleto: "Dario Santiago Mamani",
    roles: ["Productor", "Programador"],
    linkedin: "https://www.linkedin.com/in/dario-mamani-gamedesigner/",
    github: "https://github.com/mamanidario19",
    instagram: "https://www.instagram.com/mamanidario.19/",
    facebook: "",
    twitter: "",
    img: require("../assets/Fotos_Perfil/Dario.jpg"),
  },
  {
    nombreCompleto: "Ezequiel Ozan",
    roles: ["Sonidista"],
    linkedin: " ",
    github: " ",
    instagram: " ",
    facebook: " ",
    twitter: " ",
    img: require("../assets/Fotos_Perfil/Ezequiel.jpg"),
  },
  {
    nombreCompleto: "Agustin Ponce",
    roles: ["Sonidista"],
    linkedin: " ",
    github: " ",
    instagram: " ",
    facebook: " ",
    twitter: " ",
    img: require("../assets/Fotos_Perfil/Agustin.jpg"),
  },
  {
    nombreCompleto: "Evelyn Nahila Ramos",
    roles: ["Programador", "Sonidista"],
    linkedin: "https://www.linkedin.com/in/evelyn-ramos27/",
    github: "https://github.com/Evelyn027",
    instagram: "https://www.instagram.com/elyn.dev/",
    facebook: "",
    twitter: "",
    img: require("../assets/Fotos_Perfil/Evelyn.jpg"),
  },
  {
    nombreCompleto: "Aylen Cecilia Rodriguez",
    roles: ["Animador", "Narrador"],
    linkedin: " ",
    github: " ",
    instagram: " ",
    facebook: " ",
    twitter: " ",
    img: require("../assets/Fotos_Perfil/Aylen.jpg"),
  },

  {
    nombreCompleto: "Ariel Alejandro Vega",
    roles: ["Director"],
    linkedin: "https://www.linkedin.com/in/ariel-alejandro-vega/",
    github: "",
    instagram: "",
    facebook: "",
    twitter: "",
    img: require("../assets/Fotos_Perfil/Ariel.jpg"),
  },
];

export default teamData;
